name: Sync fork from upstream (0Hutch/PiggyPlugins)
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '* * * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2.1
      - name: Fork sync
        with:
          pr_title: Merge from upstream (sync fork)
